package com.gepardec.mega.rest.impl;

import com.gepardec.mega.rest.api.EmployeeWithoutTimeBookingsAndAbsentWholeMonthResource;

public class EmployeeWithoutTimeBookingsAndAbsentWholeMonthResourceImpl implements EmployeeWithoutTimeBookingsAndAbsentWholeMonthResource {
}
